/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liquidhub;

import javax.swing.JOptionPane;

/**
 *
 * @author bharatPC
 */
public class CREDIT_CARD extends javax.swing.JFrame {

    /**
     * Creates new form CREDIT_CARD
     */
    public CREDIT_CARD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("COMPLETE YOUR PAYMENT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 20, 250, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ENTER YOUR CREDIT CARD DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 100, 240, 17);

        jLabel4.setText("CARD NUMBER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 140, 120, 14);

        t1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(40, 170, 230, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MM", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(40, 250, 60, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YYYY", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(110, 250, 70, 20);

        jLabel6.setText("YEAR");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 230, 34, 14);

        jLabel5.setText("MONTH");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 230, 50, 14);
        jPanel1.add(j1);
        j1.setBounds(200, 200, 90, 20);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(40, 310, 50, 23);

        jLabel7.setText("CVV");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 290, 34, 14);

        jButton1.setText("PAY NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 360, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 588, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String card=t1.getText();
         int supersum=0;
        int len=card.length();
        if(len==16)
        {
        int a[]=new int[16];
        char b[]=new char[16];
        for(int o=0;o<len;o++)
                {
                   b[o]=card.charAt(o); 
                   
                }
      for(int z=0;z<16;z++)
      {
          a[z]=Integer.parseInt(Character.toString(b[z]));
         
      }
        
       int z=a[0];
       int arr[]=new int[16];
        for(int k=0;k<15;k=k+2)
         {
             arr[k]=a[k];
         }
        
         for(int k=0;k<15;k=k+2)
         {
             
             int y=arr[k]*2;
                     
             if (y>9)
             {
                 
                 
                    int d=y%10;
            y=y/10;
          y=y+d;
                 
             }
             
            a[k]=y; 
         }
        
        for(int j=0;j<16;j++)
        {
         supersum=supersum+a[j];
        }
        if((supersum%10)==0)
        {
           if(z==5)
           JOptionPane.showMessageDialog(null,"MASTER CARD detected ");
       if(z==4)
           JOptionPane.showMessageDialog(null,"VISA CARD detected ");
       if(z==3)
           JOptionPane.showMessageDialog(null,"AMERICAN EXPRESS CARD detected ");
            j1.setText("valid card");
            PAYMENT_COMPLETED completed=new PAYMENT_COMPLETED();
       completed.setVisible(true);
       
        }
         
            
        else
        {
           j1.setText("invalid card");
           JOptionPane.showMessageDialog(null,"The card is invalid "
                           + ".Please enter a valid card number");
        }
        }
        else
        {
             j1.setText("invalid card");
             JOptionPane.showMessageDialog(null,"the card is invalid"
                           + "plese enter a valid card number");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CREDIT_CARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CREDIT_CARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CREDIT_CARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CREDIT_CARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CREDIT_CARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel j1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
