/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liquidhub;

import javax.swing.JOptionPane;

/**
 *
 * @author bharatPC
 */
public class NET_BANKING_NEW extends javax.swing.JFrame {

    /**
     * Creates new form NET_BANKING_NEW
     */
   static String s;
    public NET_BANKING_NEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sbi = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        icici = new javax.swing.JRadioButton();
        other = new javax.swing.JComboBox<>();
        hdfc = new javax.swing.JRadioButton();
        banks = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("COMPLETE YOUR PAYMENT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 60, 250, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Choose your bank..");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 140, 130, 15);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 170);

        sbi.setText("SBI");
        sbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbiActionPerformed(evt);
            }
        });

        jButton1.setText("PAY NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        icici.setText("ICICI");

        other.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Others", "PUNJAB NATIONAL BANK", "CITY BANK", "ALLAHABAD BANK", "UCO BANK", "SYNDICATE BANK", "INDIAN BANK", "AXIS BANK", "UNION BANK" }));

        hdfc.setText("HDFC");
        hdfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hdfcActionPerformed(evt);
            }
        });

        banks.setText("Other banks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(banks)
                    .addComponent(hdfc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sbi, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icici, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sbi)
                .addGap(18, 18, 18)
                .addComponent(hdfc)
                .addGap(18, 18, 18)
                .addComponent(icici)
                .addGap(18, 18, 18)
                .addComponent(banks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hdfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hdfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hdfcActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(sbi.isSelected())
{
    s="State Bank of India";
  other.setEnabled(false);
    login_bank completed=new login_bank();
       completed.setVisible(true);
}
else if(hdfc.isSelected())
{
    s="HDFC Bank";
    other.setEnabled(false);
    login_bank completed=new login_bank();
       completed.setVisible(true);
}
else if(icici.isSelected())
{
    s="ICICI Bank";
    other.setEnabled(false);
    login_bank completed=new login_bank();
       completed.setVisible(true);
}
else if(banks.isSelected())
{
 
   s= other.getSelectedItem().toString();
   login_bank completed=new login_bank();
       completed.setVisible(true);
}
else
{
    JOptionPane.showMessageDialog(null,"Please select your bank");
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbiActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
bg.add(sbi);bg.add(hdfc);bg.add(icici);bg.add(banks);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NET_BANKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NET_BANKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NET_BANKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NET_BANKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NET_BANKING_NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton banks;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JRadioButton hdfc;
    private javax.swing.JRadioButton icici;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> other;
    private javax.swing.JRadioButton sbi;
    // End of variables declaration//GEN-END:variables
}
