/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liquidhub;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author bharatPC
 */
public class PARKING_NEW extends javax.swing.JFrame {
   static String ref1;
    /**
     * Creates new form PARKING_NEW
     */
    public PARKING_NEW() {
        initComponents();
    }
public static String ref;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        p1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        book = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton42 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton41 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        p1.setLayout(null);

        jButton1.setText("P1.1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p1.add(jButton1);
        jButton1.setBounds(50, 50, 70, 110);

        jButton8.setText("P1.8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        p1.add(jButton8);
        jButton8.setBounds(250, 180, 70, 100);

        jButton4.setText("P1.4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        p1.add(jButton4);
        jButton4.setBounds(350, 50, 70, 110);

        jButton2.setText("P1.2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p1.add(jButton2);
        jButton2.setBounds(150, 50, 70, 110);

        jButton10.setText("P1.10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        p1.add(jButton10);
        jButton10.setBounds(450, 180, 70, 100);

        jButton9.setText("P1.9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        p1.add(jButton9);
        jButton9.setBounds(350, 180, 70, 100);

        jButton7.setText("P1.7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        p1.add(jButton7);
        jButton7.setBounds(150, 180, 70, 100);

        jButton3.setText("P1.3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        p1.add(jButton3);
        jButton3.setBounds(250, 50, 70, 110);

        jButton6.setText("P1.6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        p1.add(jButton6);
        jButton6.setBounds(50, 180, 70, 100);

        jButton5.setText("P1.5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        p1.add(jButton5);
        jButton5.setBounds(450, 50, 70, 110);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE ROAD" }));
        p1.add(jComboBox1);
        jComboBox1.setBounds(30, 320, 130, 20);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Select your spot...");
        p1.add(jLabel23);
        jLabel23.setBounds(10, 10, 160, 20);
        p1.add(jLabel7);
        jLabel7.setBounds(220, 140, 0, 60);

        book.setText("BOOK");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        p1.add(book);
        book.setBounds(30, 380, 79, 23);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        p1.add(jLabel5);
        jLabel5.setBounds(0, 0, 580, 420);

        jTabbedPane1.addTab("level 1", p1);

        p2.setLayout(null);
        p2.add(jLabel20);
        jLabel20.setBounds(220, 140, 0, 60);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Select your spot...");
        p2.add(jLabel24);
        jLabel24.setBounds(10, 10, 200, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE ROAD" }));
        p2.add(jComboBox2);
        jComboBox2.setBounds(30, 320, 130, 20);

        jButton11.setText("P2.5");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        p2.add(jButton11);
        jButton11.setBounds(450, 50, 70, 110);

        jButton12.setText("P2.6");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        p2.add(jButton12);
        jButton12.setBounds(50, 180, 70, 100);

        jButton13.setText("P2.3");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        p2.add(jButton13);
        jButton13.setBounds(250, 50, 70, 110);

        jButton14.setText("P2.7");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        p2.add(jButton14);
        jButton14.setBounds(150, 180, 70, 100);

        jButton15.setText("P2.9");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        p2.add(jButton15);
        jButton15.setBounds(350, 180, 70, 100);

        jButton16.setText("P2.10");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        p2.add(jButton16);
        jButton16.setBounds(450, 180, 70, 100);

        jButton17.setText("P2.2");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        p2.add(jButton17);
        jButton17.setBounds(150, 50, 70, 110);

        jButton18.setText("P2.4");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        p2.add(jButton18);
        jButton18.setBounds(350, 50, 70, 110);

        jButton19.setText("P2.8");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        p2.add(jButton19);
        jButton19.setBounds(250, 180, 70, 100);

        jButton20.setText("P2.1");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        p2.add(jButton20);
        jButton20.setBounds(50, 50, 70, 110);

        jButton43.setText("BOOK");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        p2.add(jButton43);
        jButton43.setBounds(30, 380, 79, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        p2.add(jLabel4);
        jLabel4.setBounds(0, 0, 590, 420);

        jTabbedPane1.addTab("level2", p2);

        p3.setLayout(null);

        jButton21.setText("P3.7");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        p3.add(jButton21);
        jButton21.setBounds(150, 180, 70, 100);

        jButton22.setText("P3.6");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        p3.add(jButton22);
        jButton22.setBounds(50, 180, 70, 100);

        jButton23.setText("P3.5");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        p3.add(jButton23);
        jButton23.setBounds(450, 50, 70, 110);

        jButton24.setText("P3.9");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        p3.add(jButton24);
        jButton24.setBounds(350, 180, 70, 100);

        jButton25.setText("P3.2");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        p3.add(jButton25);
        jButton25.setBounds(150, 50, 70, 110);

        jButton26.setText("P3.3");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        p3.add(jButton26);
        jButton26.setBounds(250, 50, 70, 110);

        jButton27.setText("P3.4");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        p3.add(jButton27);
        jButton27.setBounds(350, 50, 70, 110);

        jButton28.setText("P3.8");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        p3.add(jButton28);
        jButton28.setBounds(250, 180, 70, 100);

        jButton29.setText("P3.10");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        p3.add(jButton29);
        jButton29.setBounds(450, 180, 70, 100);

        jButton30.setText("P3.1");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        p3.add(jButton30);
        jButton30.setBounds(50, 50, 70, 110);
        p3.add(jLabel29);
        jLabel29.setBounds(220, 140, 0, 60);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Select your spot...");
        p3.add(jLabel30);
        jLabel30.setBounds(10, 10, 170, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE ROAD" }));
        p3.add(jComboBox3);
        jComboBox3.setBounds(30, 320, 130, 20);

        jButton42.setText("BOOK");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        p3.add(jButton42);
        jButton42.setBounds(30, 380, 79, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        p3.add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 430);

        jTabbedPane1.addTab("level3", p3);

        p4.setLayout(null);

        jButton31.setText("P4.7");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        p4.add(jButton31);
        jButton31.setBounds(150, 180, 70, 100);

        jButton32.setText("P4.6");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        p4.add(jButton32);
        jButton32.setBounds(50, 180, 70, 100);

        jButton33.setText("P4.5");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        p4.add(jButton33);
        jButton33.setBounds(450, 50, 70, 110);

        jButton34.setText("P4.9");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        p4.add(jButton34);
        jButton34.setBounds(350, 180, 70, 100);

        jButton35.setText("P4.2");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        p4.add(jButton35);
        jButton35.setBounds(150, 50, 70, 110);

        jButton36.setText("P4.3");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        p4.add(jButton36);
        jButton36.setBounds(250, 50, 70, 110);

        jButton37.setText("P4.4");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        p4.add(jButton37);
        jButton37.setBounds(350, 50, 70, 110);

        jButton38.setText("P4.8");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        p4.add(jButton38);
        jButton38.setBounds(250, 180, 70, 100);

        jButton39.setText("P4.10");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        p4.add(jButton39);
        jButton39.setBounds(450, 180, 70, 100);

        jButton40.setText("P4.1");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        p4.add(jButton40);
        jButton40.setBounds(50, 50, 70, 110);
        p4.add(jLabel37);
        jLabel37.setBounds(220, 140, 0, 60);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("Select your spot...");
        p4.add(jLabel38);
        jLabel38.setBounds(10, 10, 102, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Locality", "GACCHIBOWLI", "HI TECH", "BANJARA HILLS", "NECKLACE ROAD" }));
        p4.add(jComboBox4);
        jComboBox4.setBounds(30, 320, 130, 20);

        jButton41.setText("BOOK");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        p4.add(jButton41);
        jButton41.setBounds(30, 380, 79, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        p4.add(jLabel2);
        jLabel2.setBounds(0, 0, 580, 420);

        jTabbedPane1.addTab("level4", p4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 590, 450);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 588, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        String loc=jComboBox4.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/liquidhub","root","Bharat@1996");
            PreparedStatement stmt = conn.prepareStatement("insert into liquidhub.parkspot values (?,?,?,?)");

            ResultSet   rs=stmt.executeQuery("select * from parkspot");
            if(p4.isShowing())
            s1 = "level-4";
            stmt.setString(1, loc);
            stmt.setString(2, s1);
            stmt.setString(3, PspotId);
            if(loc.equalsIgnoreCase("gacchibowli"))
            {
                ref= PspotId.concat("-G"); stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("banjara hills"))
            {
                ref= PspotId.concat("-B");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("hi tech"))
            {
                ref= PspotId.concat("-H");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("necklace road"))
            {
                ref= PspotId.concat("-N");
                stmt.setString(4, ref);
            }

            stmt.executeUpdate();

            stmt.close();
            conn.close();
            TIMESLOT_NEW t=new TIMESLOT_NEW();
        t.setVisible(true);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "This slot is already booked . Please chose another slot");
            System.out.println(ex);
            PARKING_NEW park=new PARKING_NEW();
            park.setVisible(true);
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        PspotId=jButton40.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        PspotId=jButton39.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        PspotId=jButton38.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        PspotId=jButton37.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        PspotId=jButton36.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        PspotId=jButton35.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        PspotId=jButton34.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        PspotId=jButton33.getText();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        PspotId=jButton32.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        PspotId=jButton31.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        String loc=jComboBox3.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/liquidhub","root","Bharat@1996");
            PreparedStatement stmt = conn.prepareStatement("insert into liquidhub.parkspot values (?,?,?,?)");

            ResultSet   rs=stmt.executeQuery("select * from parkspot");
            if(p3.isShowing())
            s1 = "level-3";
            stmt.setString(1,loc );
            stmt.setString(2, s1);
            stmt.setString(3, PspotId);
            if(loc.equalsIgnoreCase("gacchibowli"))
            {
                ref= PspotId.concat("-G");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("banjara hills"))
            {
                ref= PspotId.concat("-B");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("hi tech"))
            {
                ref = PspotId.concat("-H");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("necklace road"))
            {
                ref = PspotId.concat("-N"); stmt.setString(4, ref);
            }

            stmt.executeUpdate();
            stmt.close();
            conn.close();
            TIMESLOT_NEW t=new TIMESLOT_NEW();
        t.setVisible(true);
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "This slot is already booked . Please chose another slot");
            System.out.println(ex);
            PARKING_NEW park=new PARKING_NEW();
            park.setVisible(true);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        PspotId=jButton30.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        PspotId=jButton29.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        PspotId=jButton28.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        PspotId=jButton27.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        PspotId=jButton26.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        PspotId=jButton25.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        PspotId=jButton24.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        PspotId=jButton23.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        PspotId=jButton22.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        PspotId=jButton21.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        String loc=jComboBox2.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/liquidhub","root","Bharat@1996");
            PreparedStatement stmt = conn.prepareStatement("insert into liquidhub.parkspot values (?,?,?,?)");

            //ResultSet   rs=stmt.executeQuery("select * from parkspot");
            if(p2.isShowing())
            s1 = "level-2";
            stmt.setString(1,loc );
            stmt.setString(2, s1);
            stmt.setString(3, PspotId);
            if(loc.equalsIgnoreCase("gacchibowli"))
            {
                ref= PspotId.concat("-G");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("banjara hills"))
            {
                ref= PspotId.concat("-B");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("hi tech"))
            {
                ref= PspotId.concat("-H");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("necklace road"))
            {
                ref= PspotId.concat("-N");stmt.setString(4, ref);
            }

            stmt.executeUpdate();
            stmt.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "This slot is already booked . Please chose another slot");
            System.out.println(ex);
        }
        TIMESLOT_NEW t=new TIMESLOT_NEW();
        t.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        PspotId=jButton20.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        PspotId=jButton19.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        PspotId=jButton18.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        PspotId=jButton17.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        PspotId=jButton16.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        PspotId=jButton15.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        PspotId=jButton14.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        PspotId=jButton13.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        PspotId=jButton12.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        PspotId=jButton11.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        String loc=jComboBox1.getSelectedItem().toString();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/liquidhub","root","Bharat@1996");
            PreparedStatement stmt = conn.prepareStatement("insert into liquidhub.parkspot values (?,?,?,?)");

            ResultSet   rs=stmt.executeQuery("select * from parkspot");
            if(p1.isShowing())
            s1 = "level-1";
            /*    while(rs.next())
            {
                r=rs.getInt("Sr. no");
            }*/
            stmt.setString(1,loc );
            stmt.setString(2, s1);
            stmt.setString(3, PspotId);
            if(loc.equalsIgnoreCase("gacchibowli"))
            {
                ref= PspotId.concat("-G");
                stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("banjara hills"))
            {
                ref= PspotId.concat("-B");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("hi tech"))
            {
                ref= PspotId.concat("-H");stmt.setString(4, ref);
            }
            else if(loc.equalsIgnoreCase("necklace road"))
            {
                ref= PspotId.concat("-N");stmt.setString(4, ref);
            }

            stmt.executeUpdate();
            stmt.close();
            conn.close();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, "This slot is already booked . Please chose another slot");
            System.out.println(ex);
        }

        TIMESLOT_NEW t=new TIMESLOT_NEW();
        t.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_bookActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        PspotId=jButton5.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        PspotId=jButton6.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PspotId=jButton3.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        PspotId=jButton7.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PspotId=jButton9.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        PspotId=jButton10.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PspotId=jButton2.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PspotId=jButton4.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        PspotId=jButton8.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PspotId=jButton1.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PARKING_NEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PARKING_NEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton book;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    // End of variables declaration//GEN-END:variables
public String PspotId;
public String s1;
}
