/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liquidhub;

/**
 *
 * @author bharatPC
 */import java.sql.*;
import java.util.*;
import java.lang.*;
import java.security.*;
import javax.swing.JOptionPane;
public class REGISTER extends javax.swing.JFrame {

    /**
     * Creates new form REGISTER
     */
    Connection conn=null;
    Statement s=null;
    ResultSet rs=null;
   static final String AB = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
static SecureRandom rnd = new SecureRandom();
  static int r;
    public REGISTER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("CREATE YOUR PARK KAR ACCOUNT");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 300, 50);

        jLabel3.setText("NAME :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(120, 110, 60, 14);

        jLabel4.setText("AGE :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 154, 60, 20);

        jLabel5.setText("MOBILE NUMBER :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 210, 88, 14);

        jLabel6.setText("EMAIL ID :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 260, 80, 20);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1);
        t1.setBounds(200, 90, 160, 30);
        jPanel1.add(t2);
        t2.setBounds(200, 140, 80, 30);
        jPanel1.add(t3);
        t3.setBounds(200, 200, 160, 30);

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4);
        t4.setBounds(200, 260, 220, 30);

        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 340, 100, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\bharatPC\\Desktop\\the_one.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 590, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed


String randomString( int len ){
   StringBuilder sb = new StringBuilder( len );
   for( int i = 0; i < len; i++ ) 
      sb.append( AB.charAt( rnd.nextInt(AB.length()) ) );
   return sb.toString();
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String s1;
String a=randomString(8);
String b=t1.getText();
String c=t2.getText();
String d=t3.getText();
String e=t4.getText();
String f="0";
try{
        Class.forName("com.mysql.jdbc.Driver");
 conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3307/liquidhub","root","Bharat@1996");

PreparedStatement pst = conn.prepareStatement("insert into liquidhub.userdetail values(?,?,?,?,?,?,?)");
    
  s=conn.createStatement();
 rs=s.executeQuery("select * from userdetail");
while(rs.next())
{
 r=rs.getInt("Userid");
 s1=rs.getString("UniqueId");

}
pst.setInt(1, ++r);
 pst.setString(2, b);
 pst.setString(3, c);
 pst.setString(4, d);
 if(e.endsWith("@yahoo.com")||e.endsWith("@gmail.com")||e.endsWith("@outlook.com"))
 {
     pst.setString(5, e);
    
     
 }
 else
 {
      JOptionPane.showMessageDialog(null,"Email ID does not exist");
      throw new Exception("Cannot fill data");
 }
 pst.setString(6, a);
 pst.setString(7, f);
 int rs1=pst.executeUpdate();

 pst.close();
 conn.close();
 AFTERREAG_NEW areg=new AFTERREAG_NEW();
areg.setVisible(true);
}
catch(Exception ex)
{
    System.out.println(ex);
}


        //areg.j1.setText(s1);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
